//
// PriceAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension SwaggerClientAPI {
    
    public class PriceAPI: APIBase {
    
        /**
         
         - GET /Price/{ticker}
         - examples: [{contentType=application/json, example=[ {
  "Ticker" : "aeiou",
  "Value" : 1.3579000000000001069366817318950779736042022705078125,
  "Date" : "2016-04-04T21:17:42.040+0000"
} ]}, {contentType=application/xml, example=<null>
  <Date>2016-04-04T22:17:42.070Z</Date>
  <Ticker>string</Ticker>
  <Value>not implemented io.swagger.models.properties.DoubleProperty@a50c0d50</Value>
</null>}]
         - examples: [{contentType=application/json, example=[ {
  "Ticker" : "aeiou",
  "Value" : 1.3579000000000001069366817318950779736042022705078125,
  "Date" : "2016-04-04T21:17:42.040+0000"
} ]}, {contentType=application/xml, example=<null>
  <Date>2016-04-04T22:17:42.070Z</Date>
  <Ticker>string</Ticker>
  <Value>not implemented io.swagger.models.properties.DoubleProperty@a50c0d50</Value>
</null>}]
         
         - parameter apikey: (query) 
         - parameter ticker: (path) 

         - returns: RequestBuilder<[Price]> 
         */
        public class func priceGetByTicker(apikey apikey: String, ticker: String) -> RequestBuilder<[Price]> {
            var path = "/Price/{ticker}"
            path = path.stringByReplacingOccurrencesOfString("{ticker}", withString: "\(ticker)", options: .LiteralSearch, range: nil)
            let URLString = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [
                "apikey": apikey
            ]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<[Price]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
        }
    
        /**
         
         - GET /Price/{ticker}/{date}
         - examples: [{contentType=application/json, example={
  "Ticker" : "aeiou",
  "Value" : 1.3579000000000001069366817318950779736042022705078125,
  "Date" : "2016-04-04T21:17:42.087+0000"
}}, {contentType=application/xml, example=<null>
  <Date>2016-04-04T22:17:42.087Z</Date>
  <Ticker>string</Ticker>
  <Value>not implemented io.swagger.models.properties.DoubleProperty@a50c0d50</Value>
</null>}]
         - examples: [{contentType=application/json, example={
  "Ticker" : "aeiou",
  "Value" : 1.3579000000000001069366817318950779736042022705078125,
  "Date" : "2016-04-04T21:17:42.087+0000"
}}, {contentType=application/xml, example=<null>
  <Date>2016-04-04T22:17:42.087Z</Date>
  <Ticker>string</Ticker>
  <Value>not implemented io.swagger.models.properties.DoubleProperty@a50c0d50</Value>
</null>}]
         
         - parameter apikey: (query) 
         - parameter ticker: (path) 
         - parameter date: (path) 

         - returns: RequestBuilder<Price> 
         */
        public class func priceGet(apikey apikey: String, ticker: String, date: NSDate) -> RequestBuilder<Price> {
            var path = "/Price/{ticker}/{date}"
            path = path.stringByReplacingOccurrencesOfString("{ticker}", withString: "\(ticker)", options: .LiteralSearch, range: nil)
            path = path.stringByReplacingOccurrencesOfString("{date}", withString: "\(date)", options: .LiteralSearch, range: nil)
            let URLString = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [
                "apikey": apikey
            ]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<Price>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
        }
    
    }
}
