#
# Copyright 2015 SmartBear Software
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
#
package WWW::SwaggerClient::PriceApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;
use WWW::SwaggerClient::Configuration;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class   = shift;
    my (%self) = (
        'api_client' => WWW::SwaggerClient::ApiClient->instance,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}


#
# price_get_by_ticker
#
# 
# 
# @param string $apikey  (required)
# @param string $ticker  (required)
{
    my $params = {
    'apikey' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'ticker' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ price_get_by_ticker } = { 
    	summary => '',
        params => $params,
        returns => 'ARRAY[Price]',
        };
}
# @return ARRAY[Price]
#
sub price_get_by_ticker {
    my ($self, %args) = @_;

    
    # verify the required parameter 'apikey' is set
    unless (exists $args{'apikey'}) {
      croak("Missing the required parameter 'apikey' when calling price_get_by_ticker");
    }
    
    # verify the required parameter 'ticker' is set
    unless (exists $args{'ticker'}) {
      croak("Missing the required parameter 'ticker' when calling price_get_by_ticker");
    }
    

    # parse inputs
    my $_resource_path = '/Price/{ticker}';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json', 'text/json', 'application/xml', 'text/xml');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'apikey'}) {
        $query_params->{'apikey'} = $self->{api_client}->to_query_value($args{'apikey'});
    }
    
    # path params
    if ( exists $args{'ticker'}) {
        my $_base_variable = "{" . "ticker" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'ticker'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }
    
    my $_body_data;
    

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[Price]', $response);
    return $_response_object;
    
}

#
# price_get
#
# 
# 
# @param string $apikey  (required)
# @param string $ticker  (required)
# @param DateTime $date  (required)
{
    my $params = {
    'apikey' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'ticker' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'date' => {
        data_type => 'DateTime',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ price_get } = { 
    	summary => '',
        params => $params,
        returns => 'Price',
        };
}
# @return Price
#
sub price_get {
    my ($self, %args) = @_;

    
    # verify the required parameter 'apikey' is set
    unless (exists $args{'apikey'}) {
      croak("Missing the required parameter 'apikey' when calling price_get");
    }
    
    # verify the required parameter 'ticker' is set
    unless (exists $args{'ticker'}) {
      croak("Missing the required parameter 'ticker' when calling price_get");
    }
    
    # verify the required parameter 'date' is set
    unless (exists $args{'date'}) {
      croak("Missing the required parameter 'date' when calling price_get");
    }
    

    # parse inputs
    my $_resource_path = '/Price/{ticker}/{date}';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json', 'text/json', 'application/xml', 'text/xml');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'apikey'}) {
        $query_params->{'apikey'} = $self->{api_client}->to_query_value($args{'apikey'});
    }
    
    # path params
    if ( exists $args{'ticker'}) {
        my $_base_variable = "{" . "ticker" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'ticker'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }# path params
    if ( exists $args{'date'}) {
        my $_base_variable = "{" . "date" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'date'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }
    
    my $_body_data;
    

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Price', $response);
    return $_response_object;
    
}


1;
